# === App-wide config ===
CONFIG = {
    "tone": "satirical",  # Options: dark, funny, epic, sci-fi, mythic, chaotic, satirical, cyberpunk
}

# === Name Pools ===
# Drop-in, globally available lists for real-name generation.
# The generator will pick 70% from these pools (with anti-repeat) and 30% from AI.
# You can freely edit/expand these.

MALE_NAMES = [
    "Aaron", "Adam", "Adrian", "Aidan", "Alan", "Albert", "Alec", "Alejandro", "Alex", "Alexander",
    "Alfred", "Ali", "Allen", "Alvin", "Amir", "Andre", "Andrew", "Andy", "Anthony", "Antonio",
    "Archer", "Arjun", "Arnold", "Arthur", "Asher", "Ashton", "Austin", "Avery", "Barry", "Beau",
    "Ben", "Benedict", "Benjamin", "Bennett", "Bernard", "Bill", "Billy", "Blake", "Bob", "Bobby",
    "Bradley", "Brandon", "Braxton", "Brayden", "Brendan", "Brent", "Brett", "Brian", "Brock", "Brody",
    "Bruce", "Bryan", "Bryce", "Caleb", "Callum", "Calvin", "Cameron", "Carl", "Carlos", "Carter",
    "Casey", "Cedric", "Cesar", "Chad", "Charles", "Charlie", "Chase", "Chris", "Christian", "Christopher",
    "Clarence", "Clark", "Clayton", "Cliff", "Clifford", "Clinton", "Cody", "Colby", "Cole", "Colin",
    "Collin", "Conner", "Connor", "Conrad", "Cooper", "Corey", "Craig", "Curtis", "Cyrus", "Dale",
    "Dalton", "Damian", "Damien", "Damon", "Dan", "Daniel", "Danny", "Darren", "Daryl", "Dave",
    "David", "Dean", "Dennis", "Derek", "Desmond", "Devin", "Devon", "Dexter", "Diego", "Dominic",
    "Don", "Donald", "Donovan", "Dorian", "Doug", "Douglas", "Drake", "Drew", "Duane", "Dustin",
    "Dylan", "Earl", "Eddie", "Edgar", "Edmund", "Eduardo", "Edward", "Edwin", "Eli", "Elias",
    "Elijah", "Elliot", "Ellis", "Elmer", "Emanuel", "Emilio", "Emmanuel", "Emmett", "Enrique", "Eric",
    "Erick", "Erik", "Ernest", "Ethan", "Eugene", "Evan", "Everett", "Felix", "Fernando", "Finn",
    "Floyd", "Francis", "Francisco", "Frank", "Franklin", "Fred", "Freddie", "Frederick", "Gabriel", "Gareth",
    "Garrett", "Gary", "Gavin", "Geoffrey", "George", "Gerald", "Gilbert", "Glenn", "Gordon", "Graham",
    "Grant", "Greg", "Gregg", "Gregory", "Griffin", "Guillermo", "Gus", "Guy", "Harold", "Harrison",
    "Harry", "Harvey", "Hector", "Henry", "Herbert", "Holden", "Howard", "Hugh", "Hugo", "Hunter",
    "Ian", "Ibrahim", "Ignacio", "Isaiah", "Ismael", "Israel", "Ivan", "Jack", "Jackson", "Jacob",
    "Jake", "James", "Jamie", "Jared", "Jason", "Jasper", "Javier", "Jay", "Jayden", "Jeff",
    "Jeffrey", "Jeremiah", "Jeremy", "Jerome", "Jerry", "Jesse", "Jesus", "Jim", "Jimmy", "Joel",
    "John", "Johnny", "Jonah", "Jonathan", "Jordan", "Jorge", "Jose", "Joseph", "Josh", "Joshua",
    "Juan", "Julian", "Julius", "Justin", "Kareem", "Karl", "Keegan", "Keith", "Kelvin", "Ken",
    "Kenneth", "Kent", "Kevin", "Khalid", "Kirk", "Kris", "Kristian", "Kurt", "Kurtis", "Kyle",
    "Lance", "Larry", "Laurence", "Lawrence", "Lee", "Leo", "Leonard", "Leonardo", "Leroy", "Leslie",
    "Levi", "Liam", "Lionel", "Logan", "Lonnie", "Louis", "Lucas", "Luis", "Luke", "Luther",
    "Malcolm", "Manuel", "Marc", "Marcel", "Marco", "Marcus", "Mario", "Mark", "Marlon", "Marshall",
    "Martin", "Marvin", "Mason", "Mathew", "Matthew", "Maurice", "Max", "Maxwell", "Melvin", "Michael",
    "Miguel", "Mike", "Miles", "Milton", "Mitchell", "Morgan", "Morris", "Muhammad", "Murray", "Myles",
    "Nathan", "Nathaniel", "Neil", "Nelson", "Nicholas", "Nick", "Nigel", "Noah", "Noel", "Norman",
    "Oliver", "Omar", "Orlando", "Oscar", "Owen", "Pablo", "Parker", "Patrick", "Paul", "Pedro",
    "Percy", "Perry", "Pete", "Peter", "Philip", "Phillip", "Pierre", "Preston", "Quentin", "Quincy",
    "Quinn", "Rafael", "Ralph", "Ramon", "Randall", "Randy", "Raphael", "Raul", "Raymond", "Reece",
    "Reed", "Reese", "Reginald", "Rene", "Rex", "Ricardo", "Richard", "Rick", "Ricky", "Riley",
    "Rob", "Robbie", "Robert", "Roberto", "Robin", "Roderick", "Rodney", "Roger", "Roland", "Roman",
    "Ron", "Ronald", "Ronnie", "Rory", "Ross", "Roy", "Ruben", "Rudy", "Russell", "Ryan",
    "Sam", "Sammy", "Samuel", "Santiago", "Saul", "Scott", "Sean", "Sebastian", "Sergio", "Seth",
    "Shane", "Shannon", "Shaun", "Shawn", "Sidney", "Simon", "Spencer", "Stanley", "Stefan", "Stephen",
    "Steve", "Steven", "Stuart", "Sydney", "Tadhg", "Tanner", "Ted", "Teddy", "Terrence", "Terry",
    "Theo", "Theodore", "Thomas", "Timothy", "Toby", "Todd", "Tom", "Tomas", "Tommie", "Tommy",
    "Tony", "Travis", "Trent", "Trevor", "Trey", "Tristan", "Troy", "Tyler", "Tyrone", "Ulises",
    "Valentin", "Victor", "Vincent", "Wade", "Wallace", "Walter", "Warren", "Wayne", "Wesley", "Westley",
    "Will", "William", "Willie", "Wilson", "Winston", "Wyatt", "Xavier", "Zach", "Zachary", "Zane"
]

FEMALE_NAMES = [
    "Abigail", "Ada", "Adaline", "Adele", "Adeline", "Adriana", "Adrienne", "Aileen", "Aimee", "Aisha",
    "Aisling", "Alana", "Alayna", "Aleah", "Alejandra", "Alexa", "Alexandra", "Alexis", "Alice", "Alicia",
    "Alina", "Alisha", "Alison", "Alisson", "Alivia", "Aliyah", "Alondra", "Alyson", "Alyssa", "Amanda",
    "Amber", "Amelia", "Amelie", "Amina", "Amy", "Ana", "Anabelle", "Anastasia", "Andrea", "Angela",
    "Angelica", "Angelina", "Anita", "Ann", "Anna", "Annabelle", "Anne", "Annette", "Annie", "Annika",
    "Antonia", "April", "Aria", "Ariana", "Arianna", "Ariel", "Ariella", "Arielle", "Ashlee", "Ashley",
    "Ashlyn", "Aspen", "Astrid", "Athena", "Audrey", "Autumn", "Ava", "Avery", "Barbara", "Beatrice",
    "Becky", "Belinda", "Bella", "Bernadette", "Beth", "Bethany", "Betsy", "Betty", "Beverly", "Bianca",
    "Billie", "Blaire", "Blanca", "Bonnie", "Brandi", "Brandy", "Breanna", "Brenda", "Briana", "Brianna",
    "Bridget", "Bridgette", "Brigitte", "Brooke", "Brooklyn", "Brynn", "Cadence", "Caitlin", "Caitlyn", "Callie",
    "Camila", "Camille", "Candace", "Candice", "Cara", "Carina", "Carla", "Carlee", "Carley", "Carlie",
    "Carly", "Carmen", "Carol", "Carole", "Caroline", "Carolyn", "Carrie", "Casey", "Cassandra", "Cassidy",
    "Cassie", "Catherine", "Cathleen", "Cathy", "Cecilia", "Celeste", "Celia", "Chantal", "Charlene", "Charlotte",
    "Chelsea", "Chelsey", "Cheri", "Cheryl", "Cheyenne", "Chloe", "Chris", "Christa", "Christiana", "Christie",
    "Christina", "Christine", "Christy", "Cindy", "Claire", "Clara", "Clare", "Clarissa", "Claudia", "Colette",
    "Connie", "Constance", "Cora", "Courtney", "Cristina", "Crystal", "Cynthia", "Daisy", "Dakota", "Dana",
    "Daniela", "Daniella", "Danielle", "Daphne", "Darlene", "Dawn", "Deanna", "Deborah", "Debra", "Dee",
    "Deirdre", "Delaney", "Delia", "Denise", "Desiree", "Destiny", "Diana", "Diane", "Dianna", "Dolores",
    "Dominique", "Donna", "Dora", "Doreen", "Doris", "Dorothy", "Eden", "Edith", "Eleanor", "Elena",
    "Eliana", "Elinor", "Elisa", "Elisabeth", "Elise", "Eliza", "Elizabeth", "Ella", "Elle", "Ellen",
    "Eloise", "Elsie", "Elyse", "Ember", "Emery", "Emily", "Emma", "Erica", "Erika", "Erin",
    "Esme", "Esperanza", "Esther", "Eva", "Evelyn", "Evie", "Faith", "Faye", "Felicia", "Fernanda",
    "Fiona", "Flora", "Frances", "Francesca", "Francine", "Freya", "Gail", "Gabriela", "Gabriella", "Gabrielle",
    "Gailene", "Gemma", "Georgia", "Geraldine", "Gia", "Gianna", "Gigi", "Gilda", "Gisele", "Gladys",
    "Gloria", "Grace", "Graciela", "Gretchen", "Gwen", "Gwendolyn", "Hailey", "Haley", "Hanna", "Hannah",
    "Harriet", "Hazel", "Heather", "Heidi", "Helen", "Helena", "Holly", "Hope", "Irene", "Iris",
    "Isabella", "Isabelle", "Isla", "Ivy", "Jackie", "Jacqueline", "Jade", "Jaime", "Jane", "Janet",
    "Janice", "Janie", "Jasmine", "Jean", "Jeanette", "Jeannie", "Jenna", "Jennifer", "Jessica", "Jill",
    "Jillian", "Joan", "Joanna", "Joanne", "Jocelyn", "Jodie", "Jody", "Jordan", "Josephine", "Josie",
    "Joyce", "Judith", "Judy", "Julia", "Julianne", "Julie", "June", "Justine", "Kacey", "Kaitlin",
    "Kaitlyn", "Kala", "Kaley", "Kallie", "Kamila", "Karen", "Kari", "Karina", "Karla", "Karly",
    "Karmen", "Karolina", "Kasey", "Kassandra", "Kate", "Katelyn", "Katerina", "Katharine", "Katherine", "Kathleen",
    "Kathryn", "Kathy", "Katie", "Katrina", "Kay", "Kaya", "Kayla", "Kaylee", "Keira", "Kelsey",
    "Kendra", "Kendall", "Kennedy", "Kenya", "Kerry", "Kim", "Kimberley", "Kimberly", "Kira", "Kirsten",
    "Kit", "Kristen", "Kristi", "Kristie", "Kristin", "Kristina", "Kristine", "Kristy", "Krystal", "Kylie",
    "Kyra", "Lacey", "Laila", "Lana", "Lara", "Laura", "Lauren", "Laurie", "Layla", "Leah",
    "Leanne", "Leila", "Lena", "Leslie", "Leticia", "Liana", "Lila", "Liliana", "Lillian", "Lillie",
    "Lily", "Lina", "Linda", "Lindsay", "Lindsey", "Lisa", "Liza", "Lois", "Lola", "Loretta",
    "Lori", "Lorraine", "Louise", "Lucille", "Lucia", "Lucy", "Luisa", "Lydia", "Lyn", "Lynette",
    "Lynn", "Lynne", "Mabel", "Mackenzie", "Maddison", "Madeline", "Madison", "Mae", "Maeve", "Maggie",
    "Makayla", "Malika", "Mallory", "Mandy", "Mara", "Marcia", "Margaret", "Margarita", "Maria", "Mariam",
    "Mariana", "Marianna", "Maribel", "Marie", "Mariel", "Mariella", "Marilyn", "Marina", "Marisa", "Marisol",
    "Marissa", "Maritza", "Martha", "Martina", "Mary", "Maryann", "Matilda", "Maureen", "Maxine", "Maya",
    "Mayra", "Megan", "Meghan", "Melanie", "Melinda", "Melissa", "Melody", "Mercedes", "Meredith", "Mia",
    "Michaela", "Michelle", "Mikayla", "Mildred", "Milena", "Mindy", "Miranda", "Miriam", "Molly", "Monica",
    "Monique", "Morgan", "Muriel", "Myra", "Nadia", "Nadine", "Nancy", "Naomi", "Natalie", "Natasha",
    "Nicole", "Nina", "Noelle", "Nora", "Norma", "Norah", "Olivia", "Opal", "Paige", "Pamela",
    "Patricia", "Paula", "Pauline", "Pearl", "Peggy", "Penelope", "Penny", "Perla", "Phoebe", "Phyllis",
    "Piper", "Polly", "Priscilla", "Quinn", "Rachel", "Rachael", "Rachelle", "Ramona", "Raven", "Rebekah",
    "Reese", "Regina", "Renata", "Rhea", "Rhonda", "Riley", "Rita", "Roberta", "Robin", "Rochelle",
    "Rosa", "Rosalie", "Rosalind", "Rosanna", "Rose", "Rosemary", "Rosetta", "Rosie", "Rowena", "Roxanne",
    "Ruby", "Ruth", "Sabrina", "Sadie", "Sally", "Samantha", "Sandra", "Sara", "Sarah", "Sarai",
    "Sasha", "Savannah", "Scarlett", "Selina", "Selena", "Serena", "Shannon", "Shari", "Sharon", "Shauna",
    "Shawna", "Sheila", "Shelby", "Sherry", "Sheryl", "Shirley", "Sierra", "Simone", "Sonia", "Sonya",
    "Sophia", "Sophie", "Stacey", "Stacy", "Stefanie", "Stella", "Stephanie", "Sue", "Summer", "Susan",
    "Susanna", "Susanne", "Suzanne", "Sydney", "Sylvia", "Tabitha", "Tamara", "Tami", "Tammie", "Tammy",
    "Tanya", "Tara", "Tasha", "Tatiana", "Teresa", "Terri", "Terry", "Tessa", "Thelma", "Theresa",
    "Tiffany", "Tina", "Toni", "Tonya", "Tracey", "Traci", "Tracie", "Tracy", "Tricia", "Trina",
    "Trisha", "Trudy", "Ursula", "Valentina", "Valerie", "Vanessa", "Vera", "Veronica", "Vicki", "Vickie",
    "Victoria", "Viola", "Violet", "Virginia", "Vivian", "Wanda", "Wendy", "Whitney", "Wilma", "Winifred",
    "Wren", "Yasmine", "Yvette", "Yvonne", "Zara", "Zoe", "Zoey"
]

NEUTRAL_NAMES = [
    "Aiden", "Alex", "Ali", "Andy", "Arden", "Ari", "Ash", "Aspen", "Avery",
    "Bailey", "Beau", "Blair", "Blake", "Brett", "Briar", "Brighton", "Brook", "Campbell",
    "Casey", "Cedar", "Charlie", "Corey", "Dale", "Dallas", "Dani", "Darian", "Devon",
    "Drew", "Eden", "Ellis", "Emery", "Emerson", "Finley", "Frankie", "Gray", "Hadley",
    "Harley", "Harper", "Hayden", "Hollis", "Hunter", "Indigo", "Jaden", "Jae", "Jamie",
    "Jay", "Jesse", "Jordan", "Jules", "Kade", "Kai", "Kasey", "Keegan", "Kelly",
    "Kenzie", "Kit", "Lake", "Landon", "Lane", "Lee", "Leo", "Logan", "London",
    "Marley", "Milan", "Mika", "Monroe", "Morgan", "Noel", "Oakley", "Ollie", "Parker",
    "Pax", "Payton", "Phoenix", "Quinn", "Ray", "Reagan", "Reese", "Remy", "Riley",
    "River", "Robin", "Rowan", "Remington", "Rory", "Sage", "Sam", "Shiloh", "Sidney",
    "Sky", "Skyler", "Sloan", "Spencer", "Stevie", "Storm", "Sydney", "Tanner", "Taylor",
    "Teagan", "Toni", "Tory", "Tracy", "Tristen", "True", "Val", "Wes", "Winter",
    "Wren", "Zion"
]

LAST_NAMES = [
    "Abbott", "Abrams", "Acevedo", "Acosta", "Adkins", "Aguilar", "Aguirre", "Albertson", "Alexander", "Allen",
    "Allison", "Alvarez", "Anderson", "Andrews", "Anthony", "Armstrong", "Arnold", "Ashley", "Atkins", "Atkinson",
    "Austin", "Avery", "Avila", "Ayers", "Bailey", "Baird", "Baker", "Baldwin", "Ball", "Ballard",
    "Banks", "Barber", "Barker", "Barnett", "Barnes", "Barnhart", "Barr", "Barrett", "Barry", "Barton",
    "Bass", "Bates", "Battle", "Bauer", "Baxter", "Beach", "Bean", "Beard", "Beasley", "Beck",
    "Becker", "Bell", "Bender", "Benjamin", "Bennett", "Benson", "Bentley", "Benton", "Berger", "Bergman",
    "Bernard", "Berry", "Best", "Bird", "Bishop", "Black", "Blackburn", "Blackwell", "Blair", "Blake",
    "Blanchard", "Blankenship", "Blevins", "Boone", "Booth", "Bowen", "Bowers", "Bowman", "Boyd", "Boyer",
    "Boyle", "Brady", "Branch", "Brandt", "Braun", "Bray", "Brennan", "Brewer", "Bridges", "Briggs",
    "Bright", "Brock", "Brooks", "Brown", "Browning", "Bruce", "Bryan", "Bryant", "Buchanan", "Buck",
    "Buckley", "Bullock", "Burgess", "Burke", "Burks", "Burnett", "Burns", "Burris", "Burton", "Bush",
    "Butler", "Byers", "Byrd", "Cabrera", "Cain", "Calderon", "Caldwell", "Calhoun", "Callahan", "Camacho",
    "Cameron", "Campbell", "Campos", "Cannon", "Cantrell", "Cantu", "Cardona", "Carey", "Carlson", "Carpenter",
    "Carr", "Carroll", "Carson", "Carter", "Case", "Casey", "Castro", "Cervantes", "Chambers", "Chan",
    "Chandler", "Chang", "Chapman", "Charles", "Chase", "Chavez", "Chen", "Cherry", "Christensen", "Christian",
    "Clark", "Clarke", "Clay", "Clayton", "Clements", "Cline", "Cobb", "Cochran", "Coffey", "Cohen",
    "Cole", "Coleman", "Collier", "Collins", "Colon", "Combs", "Compton", "Conley", "Conner", "Conrad",
    "Conroy", "Cook", "Cooke", "Cooley", "Cooper", "Copeland", "Cormier", "Cortez", "Costa", "Cote",
    "Cotton", "Couch", "Courtney", "Cox", "Craig", "Crane", "Crawford", "Crosby", "Cross", "Cruz",
    "Cummings", "Cunningham", "Curry", "Curtis", "D’Angelo", "Dalton", "Daniel", "Daniels", "Davenport", "Davidson",
    "Davies", "Davis", "Dawson", "Day", "Dean", "Decker", "Delgado", "Dennis", "Diaz", "Dickerson",
    "Dickinson", "Dickson", "Dillard", "Dillon", "Dixon", "Dodson", "Dominguez", "Donaldson", "Donovan", "Dorsey",
    "Dotson", "Douglas", "Doyle", "Drake", "Duarte", "Dudley", "Duffy", "Duke", "Duncan", "Dunlap",
    "Dunn", "Duran", "Durham", "Dyer", "Eaton", "Edwards", "Elliott", "Ellis", "Ellison", "Emerson",
    "Emery", "English", "Erickson", "Escobar", "Espinoza", "Esposito", "Estes", "Estrada", "Evans", "Everett",
    "Farrell", "Faulkner", "Ferguson", "Fernandez", "Ferrell", "Fields", "Finch", "Finley", "Fischer", "Fisher",
    "Fitzgerald", "Fitzpatrick", "Fleming", "Fletcher", "Flynn", "Foley", "Forbes", "Ford", "Foreman", "Forster",
    "Foster", "Fowler", "Fox", "Francis", "Franco", "Franklin", "Fraser", "Frazier", "Frederick", "Freeman",
    "French", "Fry", "Frye", "Fuentes", "Fuller", "Fulton", "Gage", "Gaines", "Gallagher", "Gallegos",
    "Galloway", "Gamble", "Gant", "Garber", "Garcia", "Gardner", "Garner", "Garrett", "Garrison", "Garza",
    "Gates", "Gay", "Gee", "George", "Gibbs", "Gibson", "Gilbert", "Giles", "Gill", "Gillespie",
    "Gillis", "Gilmore", "Glass", "Glenn", "Glover", "Gomez", "Gonzales", "Gonzalez", "Good", "Goode",
    "Goodwin", "Gordon", "Gorman", "Gould", "Graham", "Grant", "Graves", "Gray", "Green", "Greene",
    "Greer", "Gregory", "Griffin", "Griffith", "Grimes", "Gross", "Guerra", "Guerrero", "Guthrie", "Gutierrez",
    "Guzman", "Hahn", "Hale", "Haley", "Hall", "Hamilton", "Hammond", "Hampton", "Hancock", "Haney",
    "Hansen", "Hanson", "Harding", "Hardy", "Harmon", "Harper", "Harrington", "Harris", "Harrison", "Hart",
    "Hartman", "Harvey", "Hatfield", "Hawkins", "Hayes", "Haynes", "Hays", "Heath", "Hebert", "Henderson",
    "Hendrix", "Henry", "Hensley", "Henson", "Herman", "Hernandez", "Herrera", "Hicks", "Higgins", "Hill",
    "Hines", "Hinton", "Hobbs", "Hodges", "Hoffman", "Hogan", "Holcomb", "Holden", "Holder", "Holland",
    "Holloway", "Holmes", "Holt", "Hood", "Hoover", "Hopkins", "Hopper", "Horn", "Horne", "Horton",
    "House", "Houston", "Howard", "Howe", "Howell", "Hubbard", "Hudson", "Huff", "Huffman", "Hughes",
    "Hull", "Humphrey", "Hunt", "Hunter", "Hurley", "Hurst", "Hutchinson", "Hyde", "Ingram", "Irwin",
    "Jackson", "Jacobs", "Jacobson", "James", "Jarvis", "Jefferson", "Jenkins", "Jennings", "Jensen", "Jimenez",
    "Johns", "Johnson", "Johnston", "Jones", "Jordan", "Joseph", "Joyce", "Juarez", "Justice", "Kane",
    "Kaufman", "Keith", "Kelley", "Kelly", "Kemp", "Kendall", "Kennedy", "Kent", "Kerr", "Key",
    "Kidd", "Kim", "King", "Kinney", "Kirby", "Kirk", "Klein", "Knapp", "Knight", "Knowles",
    "Knox", "Koch", "Krause", "Kramer", "Kraus", "Krueger", "Lambert", "Lamb", "Lancaster", "Landry",
    "Lane", "Lang", "Lange", "Langley", "Lara", "Larsen", "Larson", "Lawrence", "Lawson", "Leach",
    "Leal", "Leblanc", "Lee", "Leech", "Leighton", "Leon", "Leonard", "Lester", "Levine", "Levy",
    "Lewis", "Li", "Lin", "Lindsey", "Little", "Livingston", "Lloyd", "Logan", "Long", "Lopez",
    "Lord", "Love", "Lovell", "Lowe", "Lowery", "Lucas", "Luna", "Lynch", "Lynn", "Lyons",
    "MacDonald", "Macias", "Mack", "Madden", "Maddox", "Mahan", "Mahoney", "Maldonado", "Malone", "Malson",
    "Mancia", "Mancini", "Manley", "Mann", "Manning", "Manson", "Mantooth", "Mapp", "March", "Marcum",
    "Marcus", "Marek", "Marlow", "Marsh", "Marshall", "Martin", "Martinez", "Massey", "Mathews", "Mathis",
    "Matos", "Matthews", "Mattson", "Maughan", "Maxwell", "May", "Mayer", "Maynard", "Mayo", "McBride",
    "McCall", "McCann", "McCarthy", "McClain", "McClure", "McConnell", "McCormick", "McCoy", "McCray", "McCullough",
    "McDaniel", "McDonald", "McDonough", "McDowell", "McFadden", "McFarland", "McGee", "McGowan", "McGrath", "McGregor",
    "McGuire", "McIntosh", "McKay", "McKee", "McKenzie", "McKinney", "McKnight", "McLaughlin", "McLean", "McLeod",
    "McMahon", "McMillan", "McNeil", "McPherson", "Meadows", "Medina", "Meeks", "Mejia", "Melendez", "Melton",
    "Mendez", "Mendoza", "Mercer", "Merritt", "Meyer", "Meyers", "Michael", "Middleton", "Miles", "Miller",
    "Mills", "Miranda", "Mitchell", "Molina", "Monroe", "Montoya", "Moody", "Moon", "Mooney", "Moore",
    "Morales", "Moran", "Moreno", "Morgan", "Morin", "Morris", "Morrison", "Morrow", "Morse", "Morton",
    "Moses", "Moss", "Mueller", "Mullen", "Mullins", "Munoz", "Murillo", "Murphy", "Murray", "Myers",
    "Nash", "Navarro", "Neal", "Nelson", "Newman", "Newton", "Nguyen", "Nichols", "Nicholson", "Nickerson",
    "Nielsen", "Nieves", "Nixon", "Noble", "Noel", "Nolan", "Norman", "Norris", "Norton", "Novak",
    "Nunez", "O’Brien", "O’Connell", "O’Connor", "O’Donnell", "O’Neal", "O’Neill", "Ochoa", "Oliver", "Olsen",
    "Olson", "Orozco", "Ortega", "Ortiz", "Osborne", "Osborn", "Osbourne", "Osgood", "Owen", "Owens",
    "Pace", "Pacheco", "Padilla", "Page", "Palmer", "Park", "Parker", "Parks", "Parrish", "Parsons",
    "Patel", "Patrick", "Paul", "Payne", "Pearson", "Peck", "Pena", "Pendergast", "Pennington", "Perez",
    "Perkins", "Perry", "Peters", "Petersen", "Peterson", "Petty", "Phillips", "Phelps", "Pickett", "Pierce",
    "Pineda", "Pinkerton", "Pittman", "Pitts", "Pollard", "Poole", "Pope", "Porter", "Potts", "Powell",
    "Powers", "Pratt", "Preston", "Price", "Pruitt", "Puckett", "Pugh", "Quinn", "Ramirez", "Ramos",
    "Randall", "Randolph", "Rangel", "Ransom", "Rasmussen", "Ratti", "Ray", "Raymond", "Reese", "Reid",
    "Reilly", "Reiner", "Reyes", "Reynolds", "Rhodes", "Rice", "Rich", "Richard", "Richards", "Richardson",
    "Richmond", "Riddle", "Riggs", "Riley", "Rios", "Ritchie", "Rivera", "Rivers", "Roach", "Robbins",
    "Roberts", "Robertson", "Robinson", "Robles", "Rocha", "Rodgers", "Rodriguez", "Rojas", "Rollins", "Roman",
    "Romero", "Rosales", "Rosario", "Rose", "Ross", "Roth", "Rowe", "Rowland", "Roy", "Ruiz",
    "Rush", "Russell", "Russo", "Ryan", "Salas", "Salazar", "Salinas", "Salisbury", "Sampson", "Sanchez",
    "Sandoval", "Sanford", "Santana", "Santiago", "Santos", "Sargent", "Saunders", "Savage", "Sawyer", "Schaefer",
    "Schaffer", "Schmitt", "Schneider", "Schultz", "Schwartz", "Scott", "Sears", "Sellers", "Sexton", "Shaffer",
    "Shannon", "Sharp", "Shaw", "Shea", "Shelton", "Shepard", "Shepherd", "Sherman", "Shields", "Short",
    "Silva", "Simmons", "Simon", "Simpson", "Sims", "Singh", "Singleton", "Skinner", "Sloan", "Small",
    "Smith", "Snider", "Snow", "Snyder", "Solomon", "Sosa", "Soto", "Sparks", "Spears", "Spencer",
    "Stafford", "Stanley", "Stanton", "Stark", "Steele", "Stein", "Stephens", "Stephenson", "Sterling", "Stevens",
    "Stevenson", "Stewart", "Stokes", "Stone", "Stout", "Strickland", "Strong", "Stuart", "Suarez", "Sullivan",
    "Summers", "Sutton", "Swanson", "Sweeney", "Sweet", "Swift", "Talbot", "Tanner", "Tate", "Taylor",
    "Terrell", "Terry", "Thomas", "Thompson", "Thornton", "Todd", "Torres", "Townsend", "Tran", "Trevino",
    "Trujillo", "Tucker", "Turner", "Tyler", "Valdez", "Valencia", "Valenzuela", "Vance", "Vang", "Vargas",
    "Vasquez", "Vaughn", "Vega", "Velasquez", "Velez", "Villa", "Villarreal", "Vincent", "Vines", "Wade",
    "Wagner", "Walker", "Wallace", "Waller", "Walsh", "Walter", "Walters", "Walton", "Ward", "Ware",
    "Warner", "Warren", "Washington", "Waters", "Watkins", "Watson", "Watts", "Weaver", "Webb", "Weber",
    "Webster", "Weeks", "Weiss", "Welch", "Wells", "Werner", "West", "Wheeler", "Whitaker", "White",
    "Whitehead", "Whitney", "Wiggins", "Wilcox", "Wiley", "Wilkerson", "Wilkinson", "Williams", "Williamson", "Willis",
    "Wilson", "Winters", "Wise", "Wolfe", "Wong", "Wood", "Woods", "Woodward", "Wooten", "Workman",
    "Wright", "Wyatt", "Wyman", "Wynn", "Yang", "Yates", "York", "Young", "Zamora", "Zavala",
    "Zhang", "Zimmerman"
]
