# config.py
import os

# ===== App / Model Settings (env-driven; no hard-coded dev keys) =====
APP_NAME = os.getenv("APP_NAME", "AI Villain Generator")

# Text + image model defaults (override via env if you like)
OPENAI_MODEL_NAME   = os.getenv("OPENAI_MODEL_NAME", "gpt-4o-mini")
OPENAI_IMAGE_MODEL  = os.getenv("OPENAI_IMAGE_MODEL", "dall-e-3")
OPENAI_IMAGE_SIZE   = os.getenv("OPENAI_IMAGE_SIZE", "1024x1024")

# ===== Power Pools by Theme =====
# These keys match your UI style select: dark, funny, epic, sci-fi, mythic, chaotic, satirical, cyberpunk
POWER_POOLS = {
    "dark": [
        "Umbrakinesis (living shadows)",
        "Dread Pulse (fear induction)",
        "Soul Siphon (vitality drain)",
        "Night’s Veil (sight-blocking darkness)",
        "Grave Whisper (speak to the dead)",
        "Blood Hex (slow corrosive curse)",
        "Null Halo (hope suppression)",
        "Tombstep (phase through coffins/walls)",
        "Woe Stitching (bind wounds with pain)",
        "Ashen Grip (decay on touch)",
        "Black Lantern (consume light sources)",
        "Despair Beacon (area gloom aura)",
        "Bleak Fortune (bad‑luck tether)",
        "Morbid Insight (know final moments)",
        "Shivercraft (fear‑forged constructs)",
        "Eclipse Brand (mark that dims power)",
        "Quietus Breath (silence field)",
        "Funeral March (drag foes toward you)",
        "Nightmare Casting (waking visions)",
        "Coffin Warp (short-range shadow jump)",
        "Witherwave (slow structural rot)",
        "Nocturne Ward (darkness shield)",
        "Gloom Harvest (convert terror to energy)",
        "Deathknell Echo (amplify last sounds)",
        "Stygian Chains (shadow restraints)",
        "Pale Fire (cold black flame)",
        "Sable Mirror (reflect pain)",
        "Obsidian Spines (shadow spikes)",
        "Wraithwalk (intangible drift)",
        "Mourner’s Call (summon sorrow shades)",
        "Lurk Sense (detect hiding hearts)",
        "Cursed Ledger (tally and tax life)",
        "Hollow Crown (dominate weakened minds)",
        "Rot Script (curses etched into air)",
        "Gravecold (entropy burst)",
    ],
    "funny": [
        "Gag Reflex (force uncontrollable laughter)",
        "Rubber Reality (stretch body parts)",
        "Slapstick Warp (banana-peel teleport)",
        "Confetti Bombardment (dazzle + disarm)",
        "Joke‑jitsu (puns that stun)",
        "Bubble Barrage (floaty crowd control)",
        "Bonk Field (lower incoming impact)",
        "Popgun Kinesis (toy projectiles, real force)",
        "Fizzy Lift (soda‑jet spurts)",
        "Toon Mask (expressions sway moods)",
        "Pie‑ometry (pastry projectiles)",
        "Whoopee Shock (airburst knockback)",
        "Giggle Grenades (laughter clouds)",
        "Prop Swap (pull perfect prop)",
        "Slipstream Soap (friction deletion)",
        "Cartoon Hole (portable doorway disc)",
        "SFX Foley (sound effects become real)",
        "Punchline Recall (rewind 3 seconds)",
        "Foam Fortress (rapid safe barrier)",
        "Power Naps (instant micro‑rest)",
        "Balloon Armor (impact absorption)",
        "Streamer Snare (ribbon restraints)",
        "Party Pop (confusion burst)",
        "Kazooblast (sonic kazoo beam)",
        "Candy Coating (sticky immobilize)",
        "Joke Magnetism (attract attention only)",
        "Smile Sync (mood mirroring)",
        "Sticker Trap (peel‑and‑seal patches)",
        "Clown Step (silent oversized steps)",
        "Laugh Lines (drawn lines become walls)",
        "Gummy Grapple (elastic tethers)",
        "Cartoon Physics (one gag per scene)",
        "Vaudeville Vanish (trapdoor exit)",
        "Canned Laughter (crowd‑boost aura)",
        "Streamer Shield (confetti deflection)",
    ],
    "epic": [
        "Aegis Nova (radiant shield dome)",
        "Titan’s Grasp (gigantic spectral hand)",
        "Skybrand (mark enemies from above)",
        "Valor Surge (buff allies in aura)",
        "Starfall Lance (meteor javelins)",
        "Oathfire (sworn flame grows stronger)",
        "Colossus Step (quake footfalls)",
        "Hero’s Recall (snap back to banner)",
        "Glory Roar (fearless battle cry)",
        "Bannerbind (stand‑your‑ground zone)",
        "Sunward Cut (arc of daylight)",
        "Crown of Thunder (storm command)",
        "Adamantine Will (break mind control)",
        "Rune Tracer (sigil paths explode)",
        "Dragonward (anti‑beast barrier)",
        "Starlit Rally (revive downed ally)",
        "Infinite Banner (spectral cohort)",
        "Lionheart Dash (unstoppable charge)",
        "Pillar Forge (raise bulwarks)",
        "Sovereign Edict (compel single action)",
        "Beacon Step (teleport to sigils)",
        "Evershield (heal as you block)",
        "Mythic Throw (returning weapon)",
        "Anvil Echo (shockwave clap)",
        "Dawn Mantle (purge darkness)",
        "Saga Bind (name a foe, deal bonus)",
        "Arc of Triumph (projectile deflection)",
        "Titan Chain (immobilize giants)",
        "Empyrean Wake (lift allies airborne)",
        "Oathbound Strike (scales with cause)",
        "Banner of Ages (time‑slow within)",
        "Pantheon Spark (borrow archetype)",
        "Fate’s Clarion (predict next move)",
        "Kingsguard Phalanx (spectral guards)",
        "Grand Overture (orchestral buff wave)",
    ],
    "sci-fi": [
        "Electrokinesis (lightning control)",
        "Nano‑swarm fabrication",
        "Hardlight Projectors (solid holograms)",
        "Grav Shear (directional gravity cut)",
        "Phase Tunneling (matter stride)",
        "Neural Overclock (time‑dilated focus)",
        "Plasmatic Rail (coherent plasma lance)",
        "Quantum Anchor (block teleport/phase)",
        "Drone Constellation (micro‑drones)",
        "Photonic Cloak (light‑bend stealth)",
        "Ionic Net (EMP snare)",
        "Microforge (print tools on demand)",
        "Cyber Symbiosis (merge with systems)",
        "Kinetic Shunt (store/release force)",
        "Inertial Damp (impact negation)",
        "Spectral Scanner (see through matter)",
        "Retrovirus Edit (temporary bio‑mod)",
        "Null Field (anti‑power zone)",
        "Antimatter Pinprick (micro‑annihilation)",
        "Tachyon Tag (mark then time‑strike)",
        "Magnetoform (reshape metals)",
        "Thermoptic Burst (visibility erase)",
        "Data Leech (rip secrets from tech)",
        "Railstep (mag‑lev short dash)",
        "Pulse Carbine (arm‑mounted emitter)",
        "Cryo Lattice (freeze‑web)",
        "Neural Mirage (AR hallucinations)",
        "Orbital Nudge (micro‑thruster vectors)",
        "Smart Dust (perception mesh)",
        "Entropic Scrambler (weapon jam)",
        "Bio‑gel Patch (rapid heal foam)",
        "Singularity Seed (brief micro‑well)",
        "Waveform Body (brief energy shift)",
        "Ion Skates (airborne glide)",
        "Safeguard Daemon (defense AI)",
    ],
    "mythic": [
        "Rune Weaving (carve living sigils)",
        "Stormcalling (tempest command)",
        "Beast Tongue (bind mighty creatures)",
        "Fate Thread (nudge destiny)",
        "Hearthfire Boon (protective warmth)",
        "Underworld Gate (brief passage)",
        "Sun Chariot (blazing dash)",
        "Moonbinding (lunar shackles)",
        "Verdant Pact (vines and growth)",
        "Stone Sleep (granite flesh)",
        "Sky Harp (weather‑song control)",
        "Oathbinding (enforced promise)",
        "Trickster’s Mask (borrow a face)",
        "Oracle’s Sight (glimpse futures)",
        "Raven Post (spirit messenger)",
        "Tidal Crown (command waves)",
        "Titan Bone (earth‑quake strike)",
        "Ember Rite (ritual ignition)",
        "Wolfshadow (pack summons)",
        "Worldroot Step (tree‑to‑tree travel)",
        "Hero’s Mead (short burst might)",
        "Dragon Tongue (stun dragons)",
        "Mirror Lake (memory reveal)",
        "Ashen Ward (ward vs curses)",
        "Valkyrie Lift (carry fallen)",
        "Labyrinth Walk (maze conjuration)",
        "Sun‑Rune Brand (purge corruption)",
        "Thorn Oath (damage on betrayal)",
        "Lantern of Hel (spirit reveal)",
        "Basilisk Glare (petrify glance)",
        "Runic Recall (blink to sigil)",
        "Norn’s Favor (reroll fate once)",
        "Wild Hunt (relentless pursuit)",
        "Totem Guard (spirit sentries)",
        "Phoenix Gift (rebirth spark)",
    ],
    "chaotic": [
        "Dice of Doom (weighted luck)",
        "Probability Fracture (force unlikely)",
        "Entropy Touch (accelerate decay)",
        "Wild Surge (random beneficial burst)",
        "Glitchstep (unpredictable teleport)",
        "Coinflip Aegis (block or boost)",
        "Catastrophe Seed (small → big ripple)",
        "Jinx Loop (misfortune feedback)",
        "Schrödinger Palm (on/off superposition)",
        "Roulette Beam (random damage type)",
        "Chaos Net (scramble formations)",
        "Wobble Time (micro time jitters)",
        "Unstable Clone (brief chaotic double)",
        "Cascade Error (chain failures)",
        "Disorder Aura (break coordination)",
        "Quantum Trick (switch places)",
        "Gambler’s Mark (luck siphon)",
        "Spiteback (reflect random effect)",
        "Unmake Knot (undo constructs)",
        "Anomaly Pin (hold a weird zone)",
        "Bug Report (reveal hidden flaw)",
        "Tilt Reality (skew physics locally)",
        "Loaded Chance (stack odds briefly)",
        "Whimfire (random element flames)",
        "Scatter Step (split into motes)",
        "Paradox Note (erase minor event)",
        "Chaos Bargain (boon for glitch)",
        "Jam Fate (pause destiny)",
        "Entropic Bloom (radius disarray)",
        "Fortuna’s Favor (one guaranteed crit)",
        "Tumbling Deck (shuffle positions)",
        "Miscast Mirror (invert next power)",
        "Glitch Armor (flicker defense)",
        "Random Recall (blink to prior spot)",
        "Breakpoint (force system crash)",
    ],
    "satirical": [
        "Red Tape Bindings (bureaucratic snare)",
        "Cancel Field (mute influence)",
        "Spin Doctor (reframe reality)",
        "Meme Cannon (viral distraction)",
        "Algorithm Smite (downgrade priority)",
        "Terms & Conditions (compel compliance)",
        "Clickbait Lure (irresistible pull)",
        "Echo Chamber (looped opinions)",
        "Sponsored Shield (brand barrier)",
        "Fine Print (twist agreement)",
        "PR Cloak (image laundering)",
        "Public Apology (guilt debuff)",
        "Ratio Storm (overwhelm comms)",
        "TL;DR (compress info to nonsense)",
        "Focus Group (summon consensus ghosts)",
        "Engagement Trap (can’t look away)",
        "Shadowban (hide presence)",
        "Viral Hex (spread misfortune)",
        "Hot Take Overheat (tilt tempers)",
        "Bureaucracy Bomb (forms everywhere)",
        "Compliance Ping (force acknowledgement)",
        "Paywall (deny access line)",
        "Comment Deluge (noise flood)",
        "Fact‑Check Flash (reality snap)",
        "Opt‑Out Null (negate consented effect)",
        "Influencer Aura (misguided loyalty)",
        "Brand Switch (swap allegiances)",
        "NDA Veil (silence zone)",
        "DM Leak (expose secrets)",
        "Trendjack (steal momentum)",
        "Terms Revocation (void a boon)",
        "Viral Loop (retrigger last action)",
        "Cold Open (start mid‑action)",
        "Plot Armor (one improbable dodge)",
        "Fourth Wall Tap (meta interference)",
    ],
    "cyberpunk": [
        "Ghost in the Grid (stealth hacking)",
        "Black ICE Bloom (offensive counter‑AI)",
        "Synapse Overdrive (combat focus)",
        "Chrome Shield (smart armor)",
        "Neural Jack (plug‑and‑play skills)",
        "Optic Scramble (camera blindness)",
        "Drone Wrangle (commandeer swarms)",
        "Data Spike (sabotage routines)",
        "Street Surgeon (combat med‑mod)",
        "Skimmer Blades (mono‑edges)",
        "Shock Gauntlets (stun grapples)",
        "Cortex Grenade (flash‑mem spike)",
        "Spline Runner (ride fiber paths)",
        "Ghost Tag (trace through networks)",
        "Adrenal Switch (panic power)",
        "SkinWeave (impact dispersion)",
        "Black Market Backdoor (instant access)",
        "ICEbreaker Hymn (algorithmic chant)",
        "EMP Kiss (close‑range disable)",
        "Sprawl Leap (grapple urban flight)",
        "Chrome Mirage (decoy projections)",
        "Memory Scrub (erase last hour)",
        "Gridlock (freeze local traffic)",
        "Credit Siphon (drain digital funds)",
        "Firmware Hex (corrupt upgrades)",
        "Neon Quiver (hardlight bolts)",
        "Biofeedback Lash (pain feedback)",
        "Heat Sink (thermal dump)",
        "Ghostwalk Protocol (silent movement)",
        "Corporate Seal (invoke authority)",
        "Sandglass (bullet‑time burst)",
        "Packet Warp (instant data move)",
        "Subdermal Vault (hide contraband)",
        "Drone Perch (see through perch bot)",
        "Net Phantasm (fake system presence)",
    ],
}

# ===== Simple Style → Power Pool mapping =====
# Your UI styles already match these keys; this is here for clarity/forward-compat.
STYLE_TO_POWER_POOL = {
    "dark": "dark",
    "funny": "funny",
    "epic": "epic",
    "sci-fi": "sci-fi",
    "mythic": "mythic",
    "chaotic": "chaotic",
    "satirical": "satirical",
    "cyberpunk": "cyberpunk",
}

# ===== Flattened, de-duped list of all powers (optional helper) =====
def _dedupe(seq):
    seen, out = set(), []
    for s in seq:
        if s not in seen:
            out.append(s); seen.add(s)
    return out

ALL_POWERS = _dedupe([p for lst in POWER_POOLS.values() for p in lst])
